// Gestion des erreurs
/*
package main

import (
	"fmt"
	"os"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "Erreur: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	// Simuler une erreur
	return fmt.Errorf("une erreur est survenue")
}
*/